### ISSUE TITLE
Labels for CUDS objects

### ISSUE THREAD

**Issue by pablo-de-andres** [simphony/simphony-osp#298]
In GitLab by @yoavnash on Apr 22, 2020, 19:31

For the Cable Bundle Stiffness test (UrWerk project) there is a request for attaching labels to CUDS objects to help to identify them in an easier way later on. For example:
``` python
cable = EMMO.SINGLE_CABLE(label="ITWM-A1")
```
Is it beneficial to support this, even if the 'label' attribute is not explicitly specified in the ontology?

**Comment by aaronAB1993** [comment]
@yoavnash I do not see the point here. If the user wants the object of this class being specified by a label than the ontology should reflect this, right? Otherwise the same argument holds for any kind of attribute.

**Comment by yoavnash** [comment]
Well, I'm not sure about this, but I thought it could be nice if the user could add some additional information that is useful for him, but not for the ontology.

**Comment by kysrpex** [comment]
A combination of solving #416 and implementing annotation property support would solve this IMO.

**Comment by kysrpex** [comment]
Solved in SimPhoNy v4.
