### ISSUE TITLE
How should add() recursively add children?

### ISSUE THREAD

**Issue by pablo-de-andres** [simphony/simphony-osp#49]
In GitLab by @urbanmatthias on Aug 8, 2019, 10:10

Assume we call cuds1.add(cuds2) and cuds2.session is different from cuds1.session. \
In this case we have to copy cuds2 to the session of cuds1. \
Furthermore, the children (e.g. cuds enclosed by cuds2) of cuds2 need to be recursively added to the session of cuds1 as well. \
There are multiple ways to do so:

### Option 1
We only recursively add the children. \
&rarr; Most straightforward to implement

### Option 2
We recursively add the children and add relationships to parents, if they are already in cuds1.session. \
&rarr; After adding, cuds2 might have different parents in each session. 

### Option 3
We recursively add children and parents. \
&rarr; The user might not expect that the parents are also added.

### Option 4
Throw an error if cuds2 has parents which are not in cuds1.session. \
&rarr; The user has to add the parents first.

**Comment by kysrpex** [comment]
No longer a concern in SimPhoNy v4.
