### ISSUE TITLE
Allow user to specify whether CUDS should be automatically reloaded after a run()

### ISSUE THREAD

**Issue by urbanmatthias** [simphony/simphony-osp#551]
Currently CUDS objects are reloaded lazily, one by one after a simulation has been executed.

This approach is not beneficial for all scenarios, so the should be a keyword argument to let the user decide on the reload behavior:

E.g.
```py
session.run(reload=True)
session.run(reload=[<oclasses_to_reload>])
```

Anther idea is not reloading one-by-one but always also reload a neighborhood or or contained cuds when reloading.

**Comment by kysrpex** [comment]
No longer relevant in SimPhoNy v4.
