### ISSUE TITLE
OSP-core wrapper min and max version are unintuitive

### ISSUE THREAD

**Issue by urbanmatthias** [simphony/simphony-osp#568]
In the packageinfo of the wrapper, one can specify the minimum and maximum compatible version.
Unintuitively, min version is inclusive, max version is not.
I.e.
  The allowed OSP-core version for a wrapper is: min_version <= osp-core version < max version.

This can lead to confusion if osp-core version == max version

**Comment by urbanmatthias** [comment]
https://github.com/simphony/wrapper-development/blob/master/setup.py#L19-L21

**Comment by pablo-de-andres** [comment]
I believe this was chosen this way because usually it will be compatible for the same mayor and minor, and different patches.
So you don't really know what will be the last release inside a minor to specify it beforehand. So you set the next minor as the first non-compatible release.

But then `max` is certainly a confusing term for it

**Comment by ebrahimnorouzi** [comment]
I've installed osp-core version 3.5.1 and then tried to install one wrapper with these Min and Max compatible versions 

OSP_CORE_MIN = "3.3.4"
OSP_CORE_MAX = "3.4.0"

And got this error:

```
Searching for osp-core<3.4.0,>=3.3.4
Reading https://pypi.org/simple/osp-core/
Couldn't retrieve index page for 'osp-core'
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
No local packages or working download links found for osp-core<3.4.0,>=3.3.4
error: Could not find suitable distribution for Requirement.parse('osp-core<3.4.0,>=3.3.4')
```
To solve this issue, I should install osp-core again but with the version between the Min and Max. Is there another way to solve this issue?

**Comment by urbanmatthias** [comment]
Which wrapper is it?
You can also try to modify the max-version, but then no guarantee that everything works as expected.
We've put some effort to make OSP-core backwards compatible, but sometimes it is unavoidable to break some behavior.

**Comment by kysrpex** [comment]
I will close the issue as I am not enforcing nor recommending the use of the file `packageinfo.py` for SimPhoNy v4 (really not even for SimPhoNy v3). Dependencies of a package should be declared in `setupy.py` or `pyproject.toml`. There are [rules and conventions for packaging Python projects](https://packaging.python.org/) and the wheel should not be reinvented.
