### ISSUE TITLE
Generate warning message upon mismatch of OSP-core versions

### ISSUE THREAD

**Issue by yoavnash** [simphony/simphony-osp#621]
Would be helpful to have a warning message to avoid problems like this one: #619

**Comment by kysrpex** [comment]
This is simply our fault for not strictly adhering to [SemVer](https://semver.org/). The solution is that we adhere to SemVer properly. If this is the case then only major version numbers would be incompatible, but this is already implicit in the versioning policy, so no warning is needed.
