### ISSUE TITLE
Utility of Dockerfile

### ISSUE THREAD

**Issue by pablo-de-andres** [simphony/simphony-osp#829]
Now that we have published the package on Pypi, I am not sure it makes sense to maintain a Dockerfile (updating dependencies and so on), when it can be added to any Dockerfile in a one-liner.
Furthermore, Pypi gives you more control over which version to use.

**Comment by pablo-de-andres** [comment]
@yoavnash thoughts?

I believe @kysrpex agrees with me.

**Comment by yoavnash** [comment]
I see your point and agree as well.
