### ISSUE TITLE
Prune method of DbSession.

### ISSUE THREAD

**Issue by pablo-de-andres** [simphony/simphony-osp#89]
In GitLab by @urbanmatthias on Sep 26, 2019, 09:06

The session.prune() method is currently the only way to permanently delete cuds objects.

It calculates which cuds object are reachable from the root.
All cuds objects that are not reachable will be deleted.

In the case of a database session the method can become very inefficient.
It might be necessary to iterate over the entire database to calculate the reachability for an object.

Possible solution:
- Offer alternative ways to permanenty delete cuds objects (e.g. by overriding __del__)
- Override prune method in DbSession. Assume the database is connected. Consider it to be a single node in the DAG.
  All cuds objects in the registry that have a (active or passive) relationship to some element in the db
  are considered to have a (active or passive) relationship to the db node. Then:
  - All cuds objects not reachable via the registry and with no passive rel to the db node are deleted.
  - If the db node is not reachable from the root, delete the contents of the db.

See also #46

**Comment by kysrpex** [comment]
No longer relevant in SimPhoNy v4.
